/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MoveIn200ResponseAllOfDataInner {
    'accountName'?: string | null;
    'companyName'?: string | null;
    'firstName'?: string | null;
    'lastName'?: string | null;
    'unitName'?: string | null;
    /**
    * A date in YYYY-MM-DD format
    */
    'moveInDate'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string"
        },
        {
            "name": "moveInDate",
            "baseName": "moveInDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MoveIn200ResponseAllOfDataInner.attributeTypeMap;
    }
}

