/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MoveOut200ResponseAllOfDataInner {
    'accountName'?: string | null;
    'unitName'?: string | null;
    /**
    * A date in YYYY-MM-DD format
    */
    'moveOutDate'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string"
        },
        {
            "name": "moveOutDate",
            "baseName": "moveOutDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MoveOut200ResponseAllOfDataInner.attributeTypeMap;
    }
}

