/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PricingGroupAdd200ResponseAllOfDataInner {
    'groupName'?: string | null;
    /**
    * Generated from the group name if not provided
    */
    'groupDescription'?: string | null;
    /**
    * An amount in the smallest denomination (e.g. cents/pence)
    */
    'groupUnitPrice'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "groupName",
            "baseName": "groupName",
            "type": "string"
        },
        {
            "name": "groupDescription",
            "baseName": "groupDescription",
            "type": "string"
        },
        {
            "name": "groupUnitPrice",
            "baseName": "groupUnitPrice",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PricingGroupAdd200ResponseAllOfDataInner.attributeTypeMap;
    }
}

