/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReservationAdd200ResponseAllOfDataInner {
    /**
    * A person\'s full name or a company
    */
    'accountName'?: string | null;
    'companyName'?: string | null;
    'firstName'?: string | null;
    'lastName'?: string | null;
    /**
    * There is no prescribed format
    */
    'unitName'?: string | null;
    'width'?: number | null;
    'depth'?: number | null;
    'height'?: number | null;
    'features'?: Array<string> | null;
    'floor'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "depth",
            "baseName": "depth",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<string>"
        },
        {
            "name": "floor",
            "baseName": "floor",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ReservationAdd200ResponseAllOfDataInner.attributeTypeMap;
    }
}

