/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SettingsAppearance200ResponseAllOfDataInner {
    'theme'?: SettingsAppearance200ResponseAllOfDataInner.ThemeEnum;
    /**
    * Color as a word
    */
    'unitStatusColor'?: string | null;
    'showGrid'?: boolean | null;
    'showLabels'?: boolean | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "theme",
            "baseName": "theme",
            "type": "SettingsAppearance200ResponseAllOfDataInner.ThemeEnum"
        },
        {
            "name": "unitStatusColor",
            "baseName": "unitStatusColor",
            "type": "string"
        },
        {
            "name": "showGrid",
            "baseName": "showGrid",
            "type": "boolean"
        },
        {
            "name": "showLabels",
            "baseName": "showLabels",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SettingsAppearance200ResponseAllOfDataInner.attributeTypeMap;
    }
}

export namespace SettingsAppearance200ResponseAllOfDataInner {
    export enum ThemeEnum {
        Light = <any> 'light',
        Dark = <any> 'dark'
    }
}
