/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SettingsOrganization200ResponseAllOfDataInner {
    'organizationName'?: string | null;
    'description'?: string | null;
    'currency'?: string | null;
    'daysBeforeLate'?: number | null;
    'daysBeforeLien'?: number | null;
    'daysBeforeOverlock'?: number | null;
    'daysBeforeMoveOut'?: number | null;
    'prorateMoveOutThreshold'?: number | null;
    /**
    * Number of minutes
    */
    'notificationDelay'?: number | null;
    'maxReminderAttempts'?: number | null;
    'billingCycleType'?: SettingsOrganization200ResponseAllOfDataInner.BillingCycleTypeEnum;
    'timezone'?: SettingsOrganization200ResponseAllOfDataInner.TimezoneEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "organizationName",
            "baseName": "organizationName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "daysBeforeLate",
            "baseName": "daysBeforeLate",
            "type": "number"
        },
        {
            "name": "daysBeforeLien",
            "baseName": "daysBeforeLien",
            "type": "number"
        },
        {
            "name": "daysBeforeOverlock",
            "baseName": "daysBeforeOverlock",
            "type": "number"
        },
        {
            "name": "daysBeforeMoveOut",
            "baseName": "daysBeforeMoveOut",
            "type": "number"
        },
        {
            "name": "prorateMoveOutThreshold",
            "baseName": "prorateMoveOutThreshold",
            "type": "number"
        },
        {
            "name": "notificationDelay",
            "baseName": "notificationDelay",
            "type": "number"
        },
        {
            "name": "maxReminderAttempts",
            "baseName": "maxReminderAttempts",
            "type": "number"
        },
        {
            "name": "billingCycleType",
            "baseName": "billingCycleType",
            "type": "SettingsOrganization200ResponseAllOfDataInner.BillingCycleTypeEnum"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "SettingsOrganization200ResponseAllOfDataInner.TimezoneEnum"
        }    ];

    static getAttributeTypeMap() {
        return SettingsOrganization200ResponseAllOfDataInner.attributeTypeMap;
    }
}

export namespace SettingsOrganization200ResponseAllOfDataInner {
    export enum BillingCycleTypeEnum {
        FirstOfMonth = <any> 'FIRST_OF_MONTH'
    }
    export enum TimezoneEnum {
        Utc = <any> 'UTC'
    }
}
