/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SmartAction } from './smartAction';
import { SmartResponseActionData } from './smartResponseActionData';
import { SmartResponseResult } from './smartResponseResult';
import { SmartResultType } from './smartResultType';

export class SmartResponse {
    'resultType': SmartResultType;
    'result': SmartResponseResult;
    'action': SmartAction;
    'actionData': SmartResponseActionData | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resultType",
            "baseName": "resultType",
            "type": "SmartResultType"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "SmartResponseResult"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "SmartAction"
        },
        {
            "name": "actionData",
            "baseName": "actionData",
            "type": "SmartResponseActionData"
        }    ];

    static getAttributeTypeMap() {
        return SmartResponse.attributeTypeMap;
    }
}

export namespace SmartResponse {
}
