/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SmartFeature } from './smartFeature';

export class SmartResponseFilter {
    /**
    * List of features to filter
    */
    'features': Array<SmartFeature>;
    /**
    * List of floors to filter
    */
    'floors': Array<SmartFeature>;
    /**
    * Minimum price
    */
    'minPrice': number;
    /**
    * Maximum price
    */
    'maxPrice': number;
    /**
    * Length
    */
    'length': number;
    /**
    * Width
    */
    'width': number;
    /**
    * Height
    */
    'height': number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<SmartFeature>"
        },
        {
            "name": "floors",
            "baseName": "floors",
            "type": "Array<SmartFeature>"
        },
        {
            "name": "minPrice",
            "baseName": "minPrice",
            "type": "number"
        },
        {
            "name": "maxPrice",
            "baseName": "maxPrice",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SmartResponseFilter.attributeTypeMap;
    }
}

