/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum SmartResultType {
    Company = <any> 'company',
    Contact = <any> 'contact',
    Filter = <any> 'filter',
    Lease = <any> 'lease',
    Reservation = <any> 'reservation',
    Unit = <any> 'unit',
    UnitFeature = <any> 'unit-feature'
}
