/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum SmartAction {
    MoveIn = <any> 'moveIn',
    MoveOut = <any> 'moveOut',
    Reserve = <any> 'reserve',
    Invoices = <any> 'invoices',
    Transactions = <any> 'transactions'
}
