/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SmartFeature } from './smartFeature';
import { SmartResponseCompany } from './smartResponseCompany';
import { SmartResponseContact } from './smartResponseContact';
import { SmartResponseFilter } from './smartResponseFilter';
import { SmartResponseLease } from './smartResponseLease';
import { SmartResponseReservation } from './smartResponseReservation';
import { SmartResponseUnit } from './smartResponseUnit';
import { SmartResponseUnitFeature } from './smartResponseUnitFeature';

/**
* Result data
*/
export class SmartResponseResult {
    /**
    * Company ID
    */
    'companyId': string;
    /**
    * Company name
    */
    'companyName': string;
    /**
    * Mobile number
    */
    'mobileNumber': string;
    /**
    * Email
    */
    'email': string | null;
    /**
    * Contact ID
    */
    'contactId': string;
    /**
    * First name
    */
    'firstName': string;
    /**
    * Last name
    */
    'lastName': string;
    /**
    * List of features to filter
    */
    'features': Array<SmartFeature>;
    /**
    * List of floors to filter
    */
    'floors': Array<SmartFeature>;
    /**
    * Minimum price
    */
    'minPrice': number;
    /**
    * Maximum price
    */
    'maxPrice': number;
    /**
    * Length
    */
    'length': number;
    /**
    * Width
    */
    'width': number;
    /**
    * Height
    */
    'height': number | null;
    /**
    * Lease ID
    */
    'leaseId': string;
    /**
    * Account name
    */
    'accountName': string;
    /**
    * Unit ID
    */
    'unitId': string;
    /**
    * Unit name
    */
    'unitName': string;
    /**
    * Reservation ID
    */
    'reservationId': string;
    /**
    * Feature ID
    */
    'featureId': string;
    /**
    * Feature name
    */
    'featureName': string;
    /**
    * List of additional features
    */
    'additionalFeatures': Array<SmartFeature>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "companyId",
            "baseName": "companyId",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "contactId",
            "baseName": "contactId",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<SmartFeature>"
        },
        {
            "name": "floors",
            "baseName": "floors",
            "type": "Array<SmartFeature>"
        },
        {
            "name": "minPrice",
            "baseName": "minPrice",
            "type": "number"
        },
        {
            "name": "maxPrice",
            "baseName": "maxPrice",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "leaseId",
            "baseName": "leaseId",
            "type": "string"
        },
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string"
        },
        {
            "name": "reservationId",
            "baseName": "reservationId",
            "type": "string"
        },
        {
            "name": "featureId",
            "baseName": "featureId",
            "type": "string"
        },
        {
            "name": "featureName",
            "baseName": "featureName",
            "type": "string"
        },
        {
            "name": "additionalFeatures",
            "baseName": "additionalFeatures",
            "type": "Array<SmartFeature>"
        }    ];

    static getAttributeTypeMap() {
        return SmartResponseResult.attributeTypeMap;
    }
}

