/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SmartFeature } from './smartFeature';

export class SmartResponseUnitFeature {
    /**
    * Feature ID
    */
    'featureId': string;
    /**
    * Feature name
    */
    'featureName': string;
    /**
    * Minimum price
    */
    'minPrice': number;
    /**
    * Maximum price
    */
    'maxPrice': number;
    /**
    * List of additional features
    */
    'additionalFeatures': Array<SmartFeature>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "featureId",
            "baseName": "featureId",
            "type": "string"
        },
        {
            "name": "featureName",
            "baseName": "featureName",
            "type": "string"
        },
        {
            "name": "minPrice",
            "baseName": "minPrice",
            "type": "number"
        },
        {
            "name": "maxPrice",
            "baseName": "maxPrice",
            "type": "number"
        },
        {
            "name": "additionalFeatures",
            "baseName": "additionalFeatures",
            "type": "Array<SmartFeature>"
        }    ];

    static getAttributeTypeMap() {
        return SmartResponseUnitFeature.attributeTypeMap;
    }
}

