/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionProductAdd200ResponseAllOfDataInner {
    'itemName'?: string | null;
    'description'?: string | null;
    /**
    * An amount in the smallest denomination (e.g. cents/pence)
    */
    'price'?: number | null;
    'coverLevel'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "itemName",
            "baseName": "itemName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "coverLevel",
            "baseName": "coverLevel",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionProductAdd200ResponseAllOfDataInner.attributeTypeMap;
    }
}

