/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TaxRateAdd200ResponseAllOfDataInner {
    'taxTypeName'?: string | null;
    'percent'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "taxTypeName",
            "baseName": "taxTypeName",
            "type": "string"
        },
        {
            "name": "percent",
            "baseName": "percent",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TaxRateAdd200ResponseAllOfDataInner.attributeTypeMap;
    }
}

