/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dimension } from './dimension';
import { ObjectType } from './objectType';
import { Position } from './position';
import { PricingGroup } from './pricingGroup';
import { Site } from './site';
import { UnitAttribute } from './unitAttribute';
import { UnitDimensions } from './unitDimensions';
import { UnitResponseUnitReservation } from './unitResponseUnitReservation';
import { UnitSubscription } from './unitSubscription';

export class UnitResponse {
    /**
    * Unique identifier for the unit
    */
    'id': string;
    /**
    * Unique identifier for the unit
    */
    'unitId': string;
    /**
    * Unique identifier for the site the unit is located at
    */
    'siteId': string;
    'unitDimensions': UnitDimensions;
    /**
    * Dimensions of the unit(string WxL)
    */
    'dimensions': string;
    /**
    * Identifier for the set of dimensions for the unit
    */
    'dimensionsSetId': number;
    /**
    * Identifier for the metric system used for the dimensions
    */
    'metricId': number;
    'geometry': Dimension;
    'position': Position;
    /**
    * Rotation of the unit within the site
    */
    'rotation': number;
    'unitReservation': UnitResponseUnitReservation | null;
    /**
    * List of subscriptions associated with the unit
    */
    'unitSubscriptions': Array<UnitSubscription>;
    /**
    * Date and time the unit was created at
    */
    'createdAt': Date;
    /**
    * Name of the unit
    */
    'name': string;
    'site': Site;
    /**
    * Identifier for the type of object the unit is
    */
    'objectTypeId': number;
    'objectType': ObjectType;
    /**
    * Identifier for the pricing group that applies to the unit
    */
    'pricingGroupId': string;
    'pricingGroup': PricingGroup;
    /**
    * Attributes that describe features, floor, and status of the unit
    */
    'unitAttributes': Array<UnitAttribute>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "unitDimensions",
            "baseName": "unitDimensions",
            "type": "UnitDimensions"
        },
        {
            "name": "dimensions",
            "baseName": "dimensions",
            "type": "string"
        },
        {
            "name": "dimensionsSetId",
            "baseName": "dimensionsSetId",
            "type": "number"
        },
        {
            "name": "metricId",
            "baseName": "metricId",
            "type": "number"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "Dimension"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "Position"
        },
        {
            "name": "rotation",
            "baseName": "rotation",
            "type": "number"
        },
        {
            "name": "unitReservation",
            "baseName": "unitReservation",
            "type": "UnitResponseUnitReservation"
        },
        {
            "name": "unitSubscriptions",
            "baseName": "unitSubscriptions",
            "type": "Array<UnitSubscription>"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "site",
            "baseName": "site",
            "type": "Site"
        },
        {
            "name": "objectTypeId",
            "baseName": "objectTypeId",
            "type": "number"
        },
        {
            "name": "objectType",
            "baseName": "objectType",
            "type": "ObjectType"
        },
        {
            "name": "pricingGroupId",
            "baseName": "pricingGroupId",
            "type": "string"
        },
        {
            "name": "pricingGroup",
            "baseName": "pricingGroup",
            "type": "PricingGroup"
        },
        {
            "name": "unitAttributes",
            "baseName": "unitAttributes",
            "type": "Array<UnitAttribute>"
        }    ];

    static getAttributeTypeMap() {
        return UnitResponse.attributeTypeMap;
    }
}

