/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Account } from './account';
import { Lease } from './lease';

export class UnitSubscription {
    'unitId': string;
    'moveInDate': Date;
    'leaseId': string;
    'lease': Lease;
    'account': Account;
    'unitSubscriptionId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "moveInDate",
            "baseName": "moveInDate",
            "type": "Date"
        },
        {
            "name": "leaseId",
            "baseName": "leaseId",
            "type": "string"
        },
        {
            "name": "lease",
            "baseName": "lease",
            "type": "Lease"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "Account"
        },
        {
            "name": "unitSubscriptionId",
            "baseName": "unitSubscriptionId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UnitSubscription.attributeTypeMap;
    }
}

