/**
 * ManageSpace Search API
 * ManageSpace Search API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WorkflowDefinitionAdd200ResponseAllOfDataInner {
    'workflowDescription'?: string | null;
    'trigger'?: string | null;
    'steps'?: Array<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workflowDescription",
            "baseName": "workflowDescription",
            "type": "string"
        },
        {
            "name": "trigger",
            "baseName": "trigger",
            "type": "string"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowDefinitionAdd200ResponseAllOfDataInner.attributeTypeMap;
    }
}

